# Generated by Django 4.2.4 on 2023-09-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due',
        ),
    ]
